package com.app.modules.qa.controller;

import com.app.common.dto.ApiResponse;
import com.app.common.security.AuthenticatedUser;
import com.app.modules.qa.dto.OverrideRequest;
import com.app.modules.qa.dto.QaIssueOverrideResponse;
import com.app.modules.qa.dto.QaIssueResponse;
import com.app.modules.qa.service.QaService;
import jakarta.validation.Valid;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

/**
 * QA — quality gate integrated into Media Job (API_Contract.md §8). No "run QA" endpoint — issues are
 * auto-generated by the pipeline after TRANSLATE/SUMMARIZE (not built in this iteration, see
 * Backend_Java_TaskSplit_MemberB.md §7.6).
 */
@RestController
@RequestMapping("/api/workspaces/{workspaceId}")
public class QaController {

    private final QaService qaService;

    public QaController(QaService qaService) {
        this.qaService = qaService;
    }

    @GetMapping("/media/jobs/{jobId}/qa-issues")
    public ApiResponse<List<QaIssueResponse>> listIssues(@AuthenticationPrincipal AuthenticatedUser user,
                                                            @PathVariable UUID workspaceId,
                                                            @PathVariable UUID jobId,
                                                            @RequestParam(required = false) Boolean resolved) {
        List<QaIssueResponse> issues = qaService.listIssues(workspaceId, user.id(), jobId, resolved).stream()
                .map(QaIssueResponse::from)
                .toList();
        return ApiResponse.<List<QaIssueResponse>>builder().data(issues).build();
    }

    @PostMapping("/qa-issues/{issueId}/override")
    public ApiResponse<QaIssueOverrideResponse> overrideIssue(@AuthenticationPrincipal AuthenticatedUser user,
                                                                 @PathVariable UUID workspaceId,
                                                                 @PathVariable UUID issueId,
                                                                 @Valid @RequestBody OverrideRequest request) {
        var override = qaService.overrideIssue(workspaceId, user.id(), issueId, request.reason());
        return ApiResponse.<QaIssueOverrideResponse>builder().data(QaIssueOverrideResponse.from(override)).build();
    }
}
