"""Pydantic models for 4-phase provider validation (docs/07 §L, Q-PV-*)."""
from __future__ import annotations

from typing import Any, Literal, Optional

from pydantic import BaseModel

from app.schemas.contract import ProviderPayload
from app.schemas.error import ProviderErrorDetail


# ── Phase 1: CONNECTION ──────────────────────────────────────────────────────

class ConnectionProbeRequest(BaseModel):
    """Phase 1 — server reachability (no API key sent)."""
    base_url: str
    protocol: str


class ConnectionProbeResponse(BaseModel):
    ok: bool
    duration_ms: int = 0
    message: Optional[str] = None


# ── Phase 2: AUTHENTICATION ──────────────────────────────────────────────────

class AuthProbeRequest(BaseModel):
    """Phase 2 — API key validity (protocol-aware auth endpoint)."""
    protocol: str
    base_url: str
    api_key: str


class AuthProbeResponse(BaseModel):
    ok: bool
    duration_ms: int = 0
    message: Optional[str] = None


# ── Phase 3: CAPABILITY ──────────────────────────────────────────────────────

class SttProbeRequest(BaseModel):
    """Phase 3 STT — tiny transcription probe."""
    provider: ProviderPayload
    # Inline 100ms WAV bytes (base64) — generated by FastAPI, not sent by Spring Boot.
    # If omitted, FastAPI generates a minimal WAV internally.
    audio_base64: Optional[str] = None


class SttProbeResponse(BaseModel):
    ok: bool
    duration_ms: int = 0
    message: Optional[str] = None
    detected_text: Optional[str] = None
    error_detail: Optional[ProviderErrorDetail] = None


class TtsProbeRequest(BaseModel):
    """Phase 3 TTS — tiny synthesis probe.

    ``voice_id`` is optional. When omitted, FastAPI resolves a protocol default
    (Q-PV-14): DashScope → Serena, OpenAI-compatible → alloy, AUTO → first
    discovered voice. Callers (Spring Boot) should prefer resolving
    user → preset → discovery before calling this endpoint.
    """
    provider: ProviderPayload
    voice_id: Optional[str] = None
    text: str = "Hi"


class TtsProbeResponse(BaseModel):
    ok: bool
    duration_ms: int = 0
    message: Optional[str] = None
    audio_bytes: int = 0
    error_detail: Optional[ProviderErrorDetail] = None


class VisionProbeRequest(BaseModel):
    """Phase 3 VISION — prove the configured model accepts image input."""
    provider: ProviderPayload
    image_data_url: Optional[str] = None


class VisionProbeResponse(BaseModel):
    ok: bool
    duration_ms: int = 0
    message: Optional[str] = None
    detected_text: Optional[str] = None
    error_detail: Optional[ProviderErrorDetail] = None


# ── Phase 4: OPTIONAL FEATURES ──────────────────────────────────────────────

class OptionalFeatureResult(BaseModel):
    available: bool
    detail: Optional[str] = None


class FeaturesProbeRequest(BaseModel):
    """Phase 4 — probe optional features (voice/model discovery, streaming, etc.)."""
    provider: ProviderPayload


class FeaturesProbeResponse(BaseModel):
    voice_discovery: OptionalFeatureResult = OptionalFeatureResult(available=False)
    model_discovery: OptionalFeatureResult = OptionalFeatureResult(available=False)
    streaming: OptionalFeatureResult = OptionalFeatureResult(available=False)
    tool_calling: OptionalFeatureResult = OptionalFeatureResult(available=False)
    realtime: OptionalFeatureResult = OptionalFeatureResult(available=False)


# ── Aggregated ProviderTestResult ────────────────────────────────────────────

class PhaseResult(BaseModel):
    status: Literal["PASS", "FAIL", "SKIPPED"]
    duration_ms: int = 0
    message: Optional[str] = None


class ProviderTestResult(BaseModel):
    """Full 4-phase validation result returned to Spring Boot."""
    overall: Literal["PASS", "FAIL"]
    capability: str
    connection: PhaseResult
    authentication: PhaseResult
    capability_phase: PhaseResult
    optional_features: FeaturesProbeResponse
