package com.app.modules.qa.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UuidGenerator;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * QA finding on a translated/authored subtitle line (Database_Design.md §8.3). Auto-generated by the
 * pipeline after TRANSLATE/SUMMARIZE — no manual "run QA" endpoint (API_Contract.md §8).
 * {@code blocking_actions} is a subset of BLOCK_APPROVAL|BLOCK_PUBLISH|BLOCK_RENDER — {@code BLOCK_EXPORT}
 * was renamed to {@code BLOCK_PUBLISH} and {@code BLOCK_TM_WRITEBACK} was dropped (no TM in transflow_mini).
 */
@Entity
@Table(name = "qa_issues")
@Getter
@Setter
public class QaIssue {

    @Id
    @UuidGenerator
    @Column(nullable = false, updatable = false)
    private UUID id;

    @Column(name = "subtitle_segment_id", nullable = false)
    private UUID subtitleSegmentId;

    @Column(name = "issue_type", nullable = false)
    private String issueType;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 10)
    private Severity severity;

    @JdbcTypeCode(SqlTypes.ARRAY)
    @Column(name = "blocking_actions", nullable = false)
    private List<String> blockingActions;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column
    private String detail;

    @Column(name = "resolved_at")
    private Instant resolvedAt;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    public enum Severity { LOW, MEDIUM, HIGH, CRITICAL }
}
