package com.app.modules.qa.service;

import com.app.modules.qa.entity.QaIssue;
import com.app.modules.qa.entity.QaIssueOverride;

import java.util.List;
import java.util.UUID;

/**
 * QA — quality gate integrated into Media Job (API_Contract.md §8, Database_Design.md §8.3,
 * Backend_Java_TaskSplit_MemberB.md §2.6). Issues are auto-generated by the pipeline after
 * TRANSLATE/SUMMARIZE — there is no manual "run QA" endpoint.
 */
public interface QaService {

    /** {@code resolved}: null = all, true = only resolved, false = only unresolved. */
    List<QaIssue> listIssues(UUID workspaceId, UUID userId, UUID jobId, Boolean resolved);

    /**
     * Job-ownership gated (Arch §4.2): CLIENT always denied, LEAD any job, MEMBER only their own job.
     * Also denies {@code issueType}s that can never be overridden regardless of role.
     */
    QaIssueOverride overrideIssue(UUID workspaceId, UUID userId, UUID issueId, String reason);

    /**
     * Not wired to any HTTP endpoint — meant to be called by the (not-yet-built) stage executor when it
     * finds a QA problem after TRANSLATE/SUMMARIZE.
     */
    QaIssue recordIssue(UUID subtitleSegmentId, String issueType, QaIssue.Severity severity,
                        List<String> blockingActions, String detailJson);
}
