#!/usr/bin/env bash
# TransFlow — deploy trên VPS (CD gọi qua SSH; chạy tay được: cd /opt/transflow && bash deploy/server-deploy.sh).
#
# Yêu cầu có sẵn trên server: docker + compose plugin, nginx, certbot; user deploy thuộc group docker
# và chạy được `sudo -n` (hoặc là root) cho nginx/certbot.
#
# Trong APP_DIR phải có: docker-compose.prod.yml, deploy/, .env (secret ENV_PROD), .env.deploy (IMAGE_*).
# Các bước (idempotent, chạy lại bao nhiêu lần cũng được):
#   1. Kiểm tra công cụ + biến bắt buộc
#   2. nginx + Let's Encrypt (lần đầu: cấu hình HTTP tạm -> certbot webroot -> cấu hình HTTPS)
#   3. Pull image, `compose up -d`, chờ backend-main healthy
#   4. Smoke test qua HTTPS, dọn image cũ
set -Eeuo pipefail

APP_DIR="${APP_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
COMPOSE_FILE="$APP_DIR/docker-compose.prod.yml"
NGINX_CONF=/etc/nginx/conf.d/transflow.conf
REALIP_CONF=/etc/nginx/conf.d/transflow-cloudflare-realip.conf
CERT_NAME=transflow
ACME_ROOT=/var/www/certbot
HEALTH_TIMEOUT_SECONDS="${HEALTH_TIMEOUT_SECONDS:-300}"

log()  { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }
fail() { printf '\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

cd "$APP_DIR"

if [ "$(id -u)" -eq 0 ]; then SUDO=""; else SUDO="sudo -n"; fi

# Đọc 1 biến từ file env mà không `source` (giá trị secret có thể chứa ký tự đặc biệt).
env_value() {
  local key="$1" file="${2:-.env}"
  grep -E "^${key}=" "$file" | tail -n1 | cut -d= -f2- | sed -e 's/^["'\'']//' -e 's/["'\'']$//'
}

compose() {
  docker compose -f "$COMPOSE_FILE" --env-file .env --env-file .env.deploy "$@"
}

# ───────────────────────── 1. Preflight ─────────────────────────
log "Preflight"
[ -f .env ] || fail ".env not found in $APP_DIR"
[ -f .env.deploy ] || fail ".env.deploy not found in $APP_DIR"
chmod 600 .env .env.deploy
for cmd in docker nginx certbot curl; do
  command -v "$cmd" >/dev/null 2>&1 || fail "'$cmd' is not installed"
done
docker compose version >/dev/null 2>&1 || fail "docker compose plugin is not installed"
if [ -n "$SUDO" ]; then
  $SUDO true 2>/dev/null || fail "user $(whoami) needs passwordless sudo for nginx/certbot"
fi

DOMAIN="$(env_value DOMAIN)"
STORAGE_DOMAIN="$(env_value STORAGE_DOMAIN)"
WWW_DOMAIN="$(env_value WWW_DOMAIN)"; WWW_DOMAIN="${WWW_DOMAIN:-www.$DOMAIN}"
CERTBOT_EMAIL="$(env_value CERTBOT_EMAIL)"
FRONTEND_PORT="$(env_value FRONTEND_PORT)"; FRONTEND_PORT="${FRONTEND_PORT:-8081}"
MINIO_PORT="$(env_value MINIO_PORT)"; MINIO_PORT="${MINIO_PORT:-9000}"
[ -n "$DOMAIN" ] || fail "DOMAIN is empty in .env"
[ -n "$STORAGE_DOMAIN" ] || fail "STORAGE_DOMAIN is empty in .env"
[ -n "$CERTBOT_EMAIL" ] || fail "CERTBOT_EMAIL is empty in .env"

# Cú pháp compose + đủ biến bắt buộc (${VAR:?}) trước khi đụng vào gì.
compose config --quiet || fail "docker-compose.prod.yml / .env invalid"

# ───────────────────────── 2. nginx + TLS ─────────────────────────
render_nginx() {
  sed -e "s/__DOMAIN__/${DOMAIN}/g" \
      -e "s/__WWW_DOMAIN__/${WWW_DOMAIN}/g" \
      -e "s/__STORAGE_DOMAIN__/${STORAGE_DOMAIN}/g" \
      -e "s/__FRONTEND_PORT__/${FRONTEND_PORT}/g" \
      -e "s/__MINIO_PORT__/${MINIO_PORT}/g" \
      "$1" | $SUDO tee "$NGINX_CONF" >/dev/null
}

reload_nginx() {
  $SUDO nginx -t || fail "nginx config test failed"
  if $SUDO systemctl is-active --quiet nginx; then
    $SUDO systemctl reload nginx
  else
    $SUDO systemctl enable --now nginx
  fi
}

# IP client thật sau proxy Cloudflare: làm mới danh sách IP, lỗi mạng thì dùng bản trong repo.
install_cloudflare_realip() {
  local tmp v4 v6
  tmp="$(mktemp)"
  if v4="$(curl -fsS --max-time 10 https://www.cloudflare.com/ips-v4)" \
     && v6="$(curl -fsS --max-time 10 https://www.cloudflare.com/ips-v6)" \
     && [ -n "$v4" ] && [ -n "$v6" ]; then
    {
      echo "# Generated by deploy/server-deploy.sh from https://www.cloudflare.com/ips-v4|v6"
      printf '%s\n%s\n' "$v4" "$v6" | grep -E '^[0-9a-fA-F:.]+/[0-9]+$' | sed 's/.*/set_real_ip_from &;/'
      echo "real_ip_header CF-Connecting-IP;"
    } > "$tmp"
  else
    echo "Cloudflare IP list unreachable — using deploy/nginx/cloudflare-realip.conf"
    cp deploy/nginx/cloudflare-realip.conf "$tmp"
  fi
  $SUDO install -m 644 "$tmp" "$REALIP_CONF"
  rm -f "$tmp"
}

log "nginx + Let's Encrypt for $DOMAIN, $WWW_DOMAIN, $STORAGE_DOMAIN"
install_cloudflare_realip
$SUDO mkdir -p "$ACME_ROOT"
CERT_FILE="/etc/letsencrypt/live/$CERT_NAME/fullchain.pem"

if ! $SUDO test -f "$CERT_FILE"; then
  log "No certificate yet — serving ACME challenge over HTTP"
  render_nginx deploy/nginx/transflow-http.conf.template
  reload_nginx
fi

# Lần đầu: xin cert. Các lần sau: no-op nếu cert còn hạn và đủ domain (--expand khi thêm domain).
$SUDO certbot certonly --webroot -w "$ACME_ROOT" \
  --cert-name "$CERT_NAME" -d "$DOMAIN" -d "$WWW_DOMAIN" -d "$STORAGE_DOMAIN" \
  --email "$CERTBOT_EMAIL" --agree-tos --no-eff-email \
  --non-interactive --keep-until-expiring --expand \
  || fail "certbot failed — check DNS of $DOMAIN / $WWW_DOMAIN / $STORAGE_DOMAIN points to this server, port 80 is open and Cloudflare 'Always Use HTTPS' is off"

# certbot.timer (gói certbot) tự gia hạn; hook này reload nginx để dùng cert mới.
$SUDO mkdir -p /etc/letsencrypt/renewal-hooks/deploy
printf '#!/bin/sh\nsystemctl reload nginx\n' | $SUDO tee /etc/letsencrypt/renewal-hooks/deploy/reload-nginx.sh >/dev/null
$SUDO chmod 755 /etc/letsencrypt/renewal-hooks/deploy/reload-nginx.sh

render_nginx deploy/nginx/transflow.conf.template
reload_nginx

# ───────────────────────── 3. Containers ─────────────────────────
log "Pulling images ($(env_value IMAGE_TAG .env.deploy))"
compose pull --quiet

log "Starting stack"
compose up -d --remove-orphans

log "Waiting for backend-main to become healthy (timeout ${HEALTH_TIMEOUT_SECONDS}s)"
deadline=$(( $(date +%s) + HEALTH_TIMEOUT_SECONDS ))
while :; do
  status="$(docker inspect -f '{{.State.Health.Status}}' transflow-backend-main 2>/dev/null || echo missing)"
  [ "$status" = "healthy" ] && break
  if [ "$(date +%s)" -ge "$deadline" ]; then
    compose ps
    docker logs --tail 150 transflow-backend-main || true
    fail "backend-main not healthy after ${HEALTH_TIMEOUT_SECONDS}s (status: $status)"
  fi
  sleep 5
done

# frontend chờ backend-main healthy mới start — đảm bảo nó đã lên.
compose up -d frontend

# ───────────────────────── 4. Verify + cleanup ─────────────────────────
log "Smoke test"
for i in $(seq 1 12); do
  if curl -fsS -o /dev/null --max-time 10 "https://$DOMAIN/"; then
    echo "https://$DOMAIN/ OK"
    break
  fi
  [ "$i" -eq 12 ] && { compose ps; fail "https://$DOMAIN/ is not reachable"; }
  sleep 5
done
curl -sS -o /dev/null -w "https://$STORAGE_DOMAIN/minio/health/live -> %{http_code}\n" --max-time 10 \
  "https://$STORAGE_DOMAIN/minio/health/live" || true

compose ps
log "Pruning unused images older than 7 days"
docker image prune -af --filter "until=168h" >/dev/null

log "Deploy finished: https://$DOMAIN"
